#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Generate both test languages from the shared, reviewed byte fixtures."""
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
vectors = json.loads((ROOT / "fixtures/hash-vectors.json").read_text())["vectors"]
assert vectors and len({v["id"] for v in vectors}) == len(vectors)
for v in vectors:
    for key in ("preimage", "sha256", "keccak256"):
        if not re.fullmatch("[0-9a-f]{64}", v[key]):
            raise SystemExit(f"{v['id']}.{key} must be exactly 32 bytes of lowercase hex")

daml = '''-- SPDX-License-Identifier: Apache-2.0
-- Generated by scripts/generate-hash-vectors.py from fixtures/hash-vectors.json.
module Generated.HashVectors where

vectors : [(Text, Text, Text, Text)]
vectors =
'''
daml += "  [ " + "\n  , ".join("(" + ", ".join(json.dumps(v[k]) for k in ("id", "preimage", "sha256", "keccak256")) + ")" for v in vectors) + "\n  ]\n"
solidity = '''// SPDX-License-Identifier: Apache-2.0
// Generated by scripts/generate-hash-vectors.py from fixtures/hash-vectors.json.
pragma solidity ^0.8.24;

library HashVectorData {
    struct Vector { string id; bytes32 preimage; bytes32 shaDigest; bytes32 keccakDigest; }
    function vectors() internal pure returns (Vector[] memory result) {
'''
solidity += f"        result = new Vector[]({len(vectors)});\n"
for i, v in enumerate(vectors):
    solidity += f'        result[{i}] = Vector({json.dumps(v["id"])}, 0x{v["preimage"]}, 0x{v["sha256"]}, 0x{v["keccak256"]});\n'
solidity += "    }\n}\n"
outputs = {
    ROOT / "packages/conditional-lock-test/daml/Generated/HashVectors.daml": daml,
    ROOT / "contracts/evm/test/generated/HashVectorData.sol": solidity,
}
for path, content in outputs.items():
    if "--check" in sys.argv:
        if not path.exists() or path.read_text() != content:
            raise SystemExit(f"Fixture drift: run python3 scripts/generate-hash-vectors.py ({path.relative_to(ROOT)})")
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
print(f"{'Verified' if '--check' in sys.argv else 'Generated'} {len(vectors)} shared hash vectors for Daml and Solidity")
